"""Compatibility helpers for the optional PySide6 GUI stack."""

from __future__ import annotations

QT_AVAILABLE = False
QT_IMPORT_ERROR = None

try:  # pragma: no cover - depends on optional GUI extras
    from PySide6.QtCore import QByteArray, QSettings, Qt
    from PySide6.QtGui import QAction, QGuiApplication, QKeySequence, QUndoCommand, QUndoStack
    from PySide6.QtWidgets import (
        QAbstractItemView,
        QApplication,
        QButtonGroup,
        QCheckBox,
        QComboBox,
        QDialog,
        QDialogButtonBox,
        QDockWidget,
        QDoubleSpinBox,
        QFileDialog,
        QFormLayout,
        QFrame,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMenu,
        QMenuBar,
        QPlainTextEdit,
        QProgressBar,
        QPushButton,
        QSizePolicy,
        QSlider,
        QSpinBox,
        QSplitter,
        QStatusBar,
        QTabBar,
        QTabWidget,
        QTableWidget,
        QTableWidgetItem,
        QTextBrowser,
        QTextEdit,
        QToolBar,
        QToolButton,
        QTreeWidget,
        QTreeWidgetItem,
        QVBoxLayout,
        QWidget,
    )

    QT_AVAILABLE = True
except Exception as exc:  # pragma: no cover - optional dependency branch
    QT_IMPORT_ERROR = exc

__all__ = [
    "QT_AVAILABLE",
    "QT_IMPORT_ERROR",
]

if QT_AVAILABLE:  # pragma: no cover - export names only when available
    __all__ += [
        "QAction",
        "QAbstractItemView",
        "QApplication",
        "QByteArray",
        "QButtonGroup",
        "QCheckBox",
        "QComboBox",
        "QDialog",
        "QDialogButtonBox",
        "QDockWidget",
        "QDoubleSpinBox",
        "QFileDialog",
        "QFormLayout",
        "QFrame",
        "QGridLayout",
        "QGuiApplication",
        "QGroupBox",
        "QHBoxLayout",
        "QHeaderView",
        "QInputDialog",
        "QKeySequence",
        "QLabel",
        "QLineEdit",
        "QListWidget",
        "QListWidgetItem",
        "QMainWindow",
        "QMenu",
        "QMenuBar",
        "QPlainTextEdit",
        "QProgressBar",
        "QPushButton",
        "QSettings",
        "QSizePolicy",
        "QSlider",
        "QSpinBox",
        "QSplitter",
        "QStatusBar",
        "QTabBar",
        "QTabWidget",
        "QTableWidget",
        "QTableWidgetItem",
        "QTextBrowser",
        "QTextEdit",
        "QToolBar",
        "QToolButton",
        "QTreeWidget",
        "QTreeWidgetItem",
        "QUndoCommand",
        "QUndoStack",
        "QVBoxLayout",
        "QWidget",
        "Qt",
    ]
